#remote_theme: just-the-docs/just-the-docs
title: YOUR TITLE
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://paulofponciano.github.io/k8s-daily-commands-and-troubleshoot


aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/paulofponciano/ k8s-daily-commands-and-troubleshoot